language: php

sudo: false

dist: trusty

php:
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script: phpunit

matrix:
  fast_finish: true